### ISSUE TITLE
rsdmx

### ISSUE THREAD

**Issue by eblondel** [SDMX-Outreach/sdmx-tools-catalogue#4]
### Contact Details

emmanuel.blondel1@gmail.com

### Tool name

rsdmx

### Short description

rsdmx is a package to parse/read SDMX data and metadata in R. It provides a) a set of classes and methods to read data and metadata documents exchanged through the Statistical Data and Metadata Exchange (SDMX) framework. The package currently focuses on the SDMX XML standard format (SDMX-ML); and b) an interface to SDMX web-services for a list of well-known data providers, such as EUROSTAT, OECD, and others. 

### License

MIT

### Product owner

Emmanuel Blondel

### The URL for more information on your software tool

https://github.com/opensdmx/rsdmx/wiki

### The URL of a logo image for your tool

_no logo_

**Comment by OSoerensen** [comment]
Pull request created
